# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EthCanGuiUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(900, 569)
        MainWindow.setMinimumSize(QtCore.QSize(900, 569))
        MainWindow.setMaximumSize(QtCore.QSize(900, 569))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setMouseTracking(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 200, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_id_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_id_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_1.setObjectName("line_id_1")
        self.gridLayout.addWidget(self.line_id_1, 0, 1, 1, 1)
        self.line_data_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_1.setObjectName("line_data_1")
        self.gridLayout.addWidget(self.line_data_1, 0, 2, 1, 1)
        self.line_id_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_4.setObjectName("line_id_4")
        self.gridLayout.addWidget(self.line_id_4, 3, 1, 1, 1)
        self.check_send6 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send6.setText("")
        self.check_send6.setObjectName("check_send6")
        self.gridLayout.addWidget(self.check_send6, 5, 0, 1, 1)
        self.line_id_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_2.setObjectName("line_id_2")
        self.gridLayout.addWidget(self.line_id_2, 1, 1, 1, 1)
        self.line_data_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_4.setObjectName("line_data_4")
        self.gridLayout.addWidget(self.line_data_4, 3, 2, 1, 1)
        self.line_data_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_2.setObjectName("line_data_2")
        self.gridLayout.addWidget(self.line_data_2, 1, 2, 1, 1)
        self.check_send1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send1.setText("")
        self.check_send1.setChecked(True)
        self.check_send1.setTristate(False)
        self.check_send1.setObjectName("check_send1")
        self.gridLayout.addWidget(self.check_send1, 0, 0, 1, 1)
        self.line_id_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_6.setObjectName("line_id_6")
        self.gridLayout.addWidget(self.line_id_6, 5, 1, 1, 1)
        self.line_id_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_5.setObjectName("line_id_5")
        self.gridLayout.addWidget(self.line_id_5, 4, 1, 1, 1)
        self.line_data_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_6.setObjectName("line_data_6")
        self.gridLayout.addWidget(self.line_data_6, 5, 2, 1, 1)
        self.check_send4 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send4.setText("")
        self.check_send4.setObjectName("check_send4")
        self.gridLayout.addWidget(self.check_send4, 3, 0, 1, 1)
        self.check_send3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send3.setText("")
        self.check_send3.setObjectName("check_send3")
        self.gridLayout.addWidget(self.check_send3, 2, 0, 1, 1)
        self.line_data_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_5.setObjectName("line_data_5")
        self.gridLayout.addWidget(self.line_data_5, 4, 2, 1, 1)
        self.line_data_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_data_3.setObjectName("line_data_3")
        self.gridLayout.addWidget(self.line_data_3, 2, 2, 1, 1)
        self.check_send2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send2.setText("")
        self.check_send2.setObjectName("check_send2")
        self.gridLayout.addWidget(self.check_send2, 1, 0, 1, 1)
        self.line_id_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line_id_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_id_3.setObjectName("line_id_3")
        self.gridLayout.addWidget(self.line_id_3, 2, 1, 1, 1)
        self.check_send5 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_send5.setText("")
        self.check_send5.setObjectName("check_send5")
        self.gridLayout.addWidget(self.check_send5, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 100, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setObjectName("send_button")
        self.verticalLayout_2.addWidget(self.send_button)
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setObjectName("open_button")
        self.verticalLayout_2.addWidget(self.open_button)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionversion = QtWidgets.QAction(MainWindow)
        self.actionversion.setObjectName("actionversion")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EthCanGui"))
        self.label_7.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Index         ID           CAN           DLC          DIR           TIMESTAMP      DATA</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Choose Time Type"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Original Stamp"))
        self.comboBox.setItemText(1, _translate("MainWindow", "User Date"))
        self.stop_button.setText(_translate("MainWindow", "Stop Print"))
        self.save_button.setText(_translate("MainWindow", "Start Save"))
        self.line_id_1.setText(_translate("MainWindow", "0x000000"))
        self.line_data_1.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_id_4.setText(_translate("MainWindow", "0x000000"))
        self.line_id_2.setText(_translate("MainWindow", "0x000000"))
        self.line_data_4.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_data_2.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_id_6.setText(_translate("MainWindow", "0x000000"))
        self.line_id_5.setText(_translate("MainWindow", "0x000000"))
        self.line_data_6.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_data_5.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_data_3.setText(_translate("MainWindow", "00 00 00 00 00 00 00 00"))
        self.line_id_3.setText(_translate("MainWindow", "0x000000"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.actionversion.setText(_translate("MainWindow", "version"))
